const ON_CLICK_ADD_TODO_BUTTON = 'ON_CLICK_ADD_TODO_BUTTON';
const ON_CLICK_SAVE_TODO_BUTTON = 'ON_CLICK_SAVE_TODO_BUTTON';
const ON_CHANGE_TODO_DESCRIPTION = 'ON_CHANGE_TODO_DESCRIPTION';
const ON_SAVE_TODO_SUCCESS = 'ON_SAVE_TODO_SUCCESS';
const ON_CHANGE_TODO_SEARCH_INPUT = 'ON_CHANGE_TODO_SEARCH_INPUT';

export {
  ON_CLICK_ADD_TODO_BUTTON,
  ON_CLICK_SAVE_TODO_BUTTON,
  ON_CHANGE_TODO_DESCRIPTION,
  ON_SAVE_TODO_SUCCESS,
  ON_CHANGE_TODO_SEARCH_INPUT
};
